import { describe, it, expect } from 'vitest';
import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';
import {
  buildBlocks,
  assertBlocksTileTheRoad,
  chaptersInRange,
} from '../scripts/generate-stage-pages.js';

const ROOT = path.join(__dirname, '..');
const STAGES_DIR = path.join(ROOT, 'public/content/stages');
const atlas = JSON.parse(fs.readFileSync(path.join(ROOT, 'public/data/stage-chapters.json'), 'utf8'));
const config = JSON.parse(fs.readFileSync(path.join(ROOT, 'scripts/stage-pages.config.json'), 'utf8'));

const namedChapters = atlas.chapters.filter((c) => c.name);

describe('stage page block coverage', () => {
  it('tiles every named chapter across the configured blocks', () => {
    const blocks = buildBlocks(config, atlas.lastNamedStage);
    expect(() => assertBlocksTileTheRoad(blocks, atlas.chapters, atlas.lastNamedStage)).not.toThrow();
  });

  it('assigns every named chapter to exactly one block', () => {
    const blocks = buildBlocks(config, atlas.lastNamedStage);
    const counts = new Map(namedChapters.map((c) => [c.chapter, 0]));
    for (const block of blocks) {
      for (const chapter of chaptersInRange(atlas.chapters, block.start, block.end)) {
        counts.set(chapter.chapter, counts.get(chapter.chapter) + 1);
      }
    }
    const wrong = [...counts.entries()].filter(([, n]) => n !== 1);
    expect(wrong).toEqual([]);
  });

  // The failure this pins: a block boundary that misses the 20-stage chapter grid makes
  // chaptersInRange drop the straddling chapter from every page, silently losing content.
  it('refuses a block boundary that does not land on a chapter edge', () => {
    const broken = {
      ...config,
      pages: config.pages.map((p, i) => (i === 1 ? { ...p, end: p.end - 10 } : p)),
    };
    const blocks = buildBlocks(broken, atlas.lastNamedStage);
    expect(() => assertBlocksTileTheRoad(blocks, atlas.chapters, atlas.lastNamedStage)).toThrow(
      /fall outside every configured block/
    );
  });

  it('drops blocks that start beyond the end of the named road', () => {
    const blocks = buildBlocks(config, config.pages[0].end);
    expect(blocks).toHaveLength(1);
    expect(blocks[0].end).toBeGreaterThanOrEqual(blocks[0].start);
  });
});

describe('generated stage pages', () => {
  const files = fs
    .readdirSync(STAGES_DIR)
    .filter((f) => f.startsWith('stages-') && f.endsWith('.md'));

  it('emits one page per configured block', () => {
    expect(files).toHaveLength(config.pages.length);
  });

  // The marker cannot live in frontmatter: the page editor validates frontmatter against
  // a fixed allowlist and blocks saving on anything else, so a `generated: true` key
  // would leave every block page openable but unsaveable for contributors (pinned by
  // tests/content-frontmatter.test.js). The HTML comment below the frontmatter carries
  // it instead - the first thing anyone editing the raw markdown sees.
  it('marks every generated page so hand edits are not lost silently', () => {
    for (const file of files) {
      const { content } = matter(fs.readFileSync(path.join(STAGES_DIR, file), 'utf8'));
      expect(content.trimStart(), `${file} is missing its generated-by comment`).toMatch(
        /^<!-- Generated by scripts\/generate-stage-pages\.js\b/
      );
      expect(content, `${file} does not point editors at the prose config`).toContain(
        'scripts/stage-pages.config.json'
      );
    }
  });

  // A chapter is tabulated (its own heading plus stage tables) only when all
  // twenty of its stages are at or below the verified boundary; deeper
  // chapters are listed by name in the page's "Chapters In This Stretch"
  // table only, under one notice, so the page never repeats "no figures".
  const bodies = new Map(files.map((file) => [file, fs.readFileSync(path.join(STAGES_DIR, file), 'utf8')]));
  const isVerified = (chapter) => chapter.lastStage <= atlas.lastVerifiedStage;
  const headingIn = (body, chapter) => body.includes(`>${chapter.chapter}. ${chapter.name} `);
  const tableRowIn = (body, chapter) => body.includes(`| ${chapter.chapter} | **${chapter.name}** |`);

  it('splits the named chapters at the verified boundary', () => {
    expect(namedChapters.some(isVerified)).toBe(true);
    expect(namedChapters.some((c) => !isVerified(c))).toBe(true);
  });

  it('gives every verified chapter a heading on exactly one page', () => {
    const counts = new Map();
    for (const body of bodies.values()) {
      for (const chapter of namedChapters.filter(isVerified)) {
        if (headingIn(body, chapter)) counts.set(chapter.chapter, (counts.get(chapter.chapter) ?? 0) + 1);
      }
    }
    const missing = namedChapters.filter(isVerified).filter((c) => !counts.has(c.chapter)).map((c) => c.chapter);
    const duplicated = [...counts.entries()].filter(([, n]) => n > 1).map(([c]) => c);
    expect({ missing, duplicated }).toEqual({ missing: [], duplicated: [] });
  });

  it('lists every unverified chapter by name on exactly one page, with no heading and no stage rows', () => {
    const rows = new Map();
    for (const [file, body] of bodies) {
      for (const chapter of namedChapters.filter((c) => !isVerified(c))) {
        expect(headingIn(body, chapter), `${file} tabulates unverified chapter ${chapter.chapter}`).toBe(false);
        if (tableRowIn(body, chapter)) rows.set(chapter.chapter, (rows.get(chapter.chapter) ?? 0) + 1);
      }
    }
    const missing = namedChapters.filter((c) => !isVerified(c)).filter((c) => !rows.has(c.chapter)).map((c) => c.chapter);
    const duplicated = [...rows.entries()].filter(([, n]) => n > 1).map(([c]) => c);
    expect({ missing, duplicated }).toEqual({ missing: [], duplicated: [] });
  });

  it('explains the missing figures once per page that lists unverified chapters, and nowhere else', () => {
    for (const [file, body] of bodies) {
      const listsUnverified = namedChapters.some((c) => !isVerified(c) && tableRowIn(body, c));
      const notices = (body.match(/\*\*Numbers stop at stage [\d,]+\.\*\*/g) || []).length;
      expect(notices, file).toBe(listsUnverified ? 1 : 0);
    }
  });

  it('never publishes a stage row past the verified boundary', () => {
    const stageRows = [...bodies.values()].flatMap((body) =>
      [...body.matchAll(/^\| \*\*(\d+)\*\* \|/gm)].map((m) => Number(m[1]))
    );
    expect(stageRows.length).toBeGreaterThan(0);
    const deepest = Math.max(...stageRows);
    expect(Number.isFinite(deepest)).toBe(true);
    expect(deepest).toBeLessThanOrEqual(atlas.lastVerifiedStage);
    // The tables really do reach the boundary rather than stopping early.
    expect(deepest).toBeGreaterThan(atlas.lastVerifiedStage - 20);
  });
});
