/**
 * ContributionBanner Component - Slayer Legend Wiki customization
 *
 * Wraps the framework's ContributionBanner with game-specific messages
 */

import React from 'react';
import PropTypes from 'prop-types';
import FrameworkContributionBanner from '../../wiki-framework/src/components/common/ContributionBanner.jsx';

const ContributionBanner = ({ type = 'ai-generated' }) => {
  // Game-specific messages
  const customMessages = {
    'ai-generated': {
      message: 'This page was generated by AI but it\'s ready for a human touch! Share your valuable insight and become a contributor to the Slayer Legend Wiki! We need your help to get proper useful information.',
      footer: 'Maybe you\'ll become a top contributor in the highscores, Slayer!',
    },
  };

  const custom = customMessages[type] || customMessages['ai-generated'];

  return (
    <FrameworkContributionBanner
      type={type}
      customMessage={custom.message}
      customFooter={custom.footer}
    />
  );
};

ContributionBanner.propTypes = {
  type: PropTypes.string,
};

export default ContributionBanner;
