import React from 'react';
import PropTypes from 'prop-types';

/**
 * ContributionBanner - A stylized banner encouraging community contributions
 * Used on AI-generated pages to invite human input and corrections
 */
const ContributionBanner = ({ type = 'ai-generated' }) => {
  const bannerStyles = {
    container: {
      margin: '2rem 0',
      padding: '1.5rem',
      borderLeft: '4px solid #4a9eff',
      backgroundColor: 'rgba(74, 158, 255, 0.1)',
      borderRadius: '4px',
    },
    title: {
      margin: '0 0 0.75rem 0',
      fontSize: '1.1rem',
      fontWeight: 'bold',
      color: '#4a9eff',
    },
    message: {
      margin: '0.5rem 0',
      lineHeight: '1.6',
    },
    disclaimer: {
      margin: '0.5rem 0',
      lineHeight: '1.6',
      fontStyle: 'italic',
      opacity: 0.85,
    },
    footer: {
      margin: '0.75rem 0 0 0',
      fontSize: '0.875rem',
      fontStyle: 'italic',
      opacity: 0.7,
      paddingLeft: '1rem',
      borderLeft: '2px solid rgba(74, 158, 255, 0.3)',
    },
  };

  const messages = {
    'ai-generated': {
      title: '🤖 Community Contribution Opportunity',
      message: 'This page was generated by AI but it\'s ready for a human touch! Share your valuable insight and become a contributor to the Slayer Legend Wiki! We need your help to get proper useful information.',
      footer: 'Maybe you\'ll become a top contributor in the highscores, Slayer!',
    },
  };

  const content = messages[type] || messages['ai-generated'];

  return (
    <div style={bannerStyles.container}>
      <div style={bannerStyles.title}>{content.title}</div>
      <div style={bannerStyles.message}>{content.message}</div>
      <div style={bannerStyles.footer}>{content.footer}</div>
    </div>
  );
};

ContributionBanner.propTypes = {
  type: PropTypes.string,
};

export default ContributionBanner;
