#!/usr/bin/env node
/**
 * Check Git Commit for Cache Purge Keyword
 *
 * Reads the latest git commit message and checks for cache purge keywords.
 * If found, sets VITE_PURGE_CLIENT_CACHE=true for the build process.
 *
 * Keywords that trigger cache purge:
 * - [purge-cache]
 * - [purge cache]
 * - PURGE_CACHE
 * - purge cache (case insensitive)
 */

import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * Get the latest git commit message
 * @returns {string} Commit message or empty string
 */
function getLatestCommitMessage() {
  try {
    const message = execSync('git log -1 --pretty=%B', {
      encoding: 'utf8',
      stdio: ['pipe', 'pipe', 'ignore'],
    }).trim();

    console.log('[CachePurgeCheck] Latest commit message:', message);
    return message;
  } catch (error) {
    console.warn('[CachePurgeCheck] Failed to get commit message:', error.message);
    return '';
  }
}

/**
 * Check if commit message contains cache purge keywords
 * @param {string} message - Commit message
 * @returns {boolean} True if cache purge keyword found
 */
function shouldPurgeCache(message) {
  const keywords = [
    /\[purge-cache\]/i,
    /\[purge cache\]/i,
    /PURGE_CACHE/,
    /purge cache/i,
  ];

  return keywords.some(keyword => keyword.test(message));
}

/**
 * Set environment variable for build process
 */
function setEnvironmentVariable() {
  const envPath = path.join(__dirname, '..', '.env.production.local');

  try {
    // Append to .env.production.local (or create if doesn't exist)
    const envContent = '\n# Auto-generated by checkCommitForCachePurge.js\nVITE_PURGE_CLIENT_CACHE=true\n';
    fs.appendFileSync(envPath, envContent);

    console.log('[CachePurgeCheck] ✓ Set VITE_PURGE_CLIENT_CACHE=true in .env.production.local');
  } catch (error) {
    console.error('[CachePurgeCheck] Failed to set environment variable:', error.message);
  }
}

/**
 * Main execution
 */
function checkCommitForCachePurge() {
  console.log('[CachePurgeCheck] Checking commit message for cache purge keyword...');

  const commitMessage = getLatestCommitMessage();

  if (!commitMessage) {
    console.log('[CachePurgeCheck] No commit message found, skipping cache purge check');
    return;
  }

  if (shouldPurgeCache(commitMessage)) {
    console.log('[CachePurgeCheck] 🔥 Cache purge keyword detected!');
    setEnvironmentVariable();
  } else {
    console.log('[CachePurgeCheck] No cache purge keyword found');
  }
}

// Run when executed directly
checkCommitForCachePurge();

export { checkCommitForCachePurge, getLatestCommitMessage, shouldPurgeCache };
