import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * Generate public/ads.txt from features.ads.adsense.client in wiki-config.json
 *
 * ads.txt tells programmatic buyers which sellers are authorised to sell this
 * site's inventory. A MISSING file is fine; a file that exists but does not list
 * google.com is worse than nothing - buyers read that as "unauthorised" and stop
 * bidding. So this script only writes the file once a publisher ID is configured,
 * and removes a previously generated file if the ID is cleared.
 *
 * f08c47fec0942fa0 is Google's fixed certification authority ID for AdSense.
 */

const GOOGLE_CERTIFICATION_AUTHORITY_ID = 'f08c47fec0942fa0';
const GENERATED_MARKER = '# Generated by scripts/generateAdsTxt.js - edit wiki-config.json instead';

const configPath = path.join(__dirname, '..', 'wiki-config.json');
const adsTxtPath = path.join(__dirname, '..', 'public', 'ads.txt');

try {
  const config = JSON.parse(fs.readFileSync(configPath, 'utf8'));
  const ads = config?.features?.ads;
  const client = ads?.adsense?.client?.trim() || '';

  if (!client) {
    // Only remove a file we generated - never clobber a hand-maintained ads.txt
    if (fs.existsSync(adsTxtPath) && fs.readFileSync(adsTxtPath, 'utf8').includes(GENERATED_MARKER)) {
      fs.unlinkSync(adsTxtPath);
      console.log('✓ Removed generated public/ads.txt (no AdSense client configured)');
    } else {
      console.log('- Skipping ads.txt (features.ads.adsense.client is not set)');
    }
    process.exit(0);
  }

  // ads.txt wants the bare publisher ID, without the "ca-" prefix used in page code
  const publisherId = client.replace(/^ca-/, '');

  const contents = [
    GENERATED_MARKER,
    `google.com, ${publisherId}, DIRECT, ${GOOGLE_CERTIFICATION_AUTHORITY_ID}`,
    '',
  ].join('\n');

  fs.mkdirSync(path.dirname(adsTxtPath), { recursive: true });
  fs.writeFileSync(adsTxtPath, contents, 'utf8');
  console.log(`✓ Wrote public/ads.txt for ${publisherId}`);
} catch (err) {
  console.error('Failed to generate ads.txt:', err.message);
  process.exit(1);
}
